version: 2.1

orbs:
  node: circleci/node@4.3.0

jobs:
  test-with-node:
    parameters:
      node-version:
        type: string
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-yarn: true
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test

workflows:
  build_and_test:
    jobs:
      - test-with-node:
          matrix:
            parameters:
              node-version: ["20", "22"]
